### ISSUE TITLE
Shawarma Side Car throttling CPU with default resource settings

### ISSUE THREAD

**Issue by tcrozier** [CenterEdge/shawarma-webhook#25]
**Describe the bug**
When observing the Shawarma side car container for CPU Throttling it was observed that it would routinely run at a 40% level across multiple services that use it. While it is an option to override the default value of 10m for both requests and limits ([https://github.com/CenterEdge/shawarma-webhook#customizing-the-sidecar]) it might be better to increase the default value if the is a more widespread issue. During my testing it was observed that 25m would be a better value for both requests and limits.

**To Reproduce**
1. Run an application that uses the Shawarma side car container
2. Observe the CPU throttling value reported via Prometheus or other metrics tool

**Expected behavior**
While a small amount of throttling is probably acceptable a consistent 40% is too high

**Additional context**
Modifying the requests and limits to 25m fixed the problem for me.

**Comment by brantburnett** [comment]
Fixed by #28
